version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight. 
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight
        tests:
          - positive_values
  - name: stg_addresses
    description: Contains every unique address on platform

  - name: stg_users 
    description: Contains every unique user on platform 

  - name: stg_promos 
    description: Contains every unique promo code on platform
        
  - name: stg_products 
    description: Contains every unique product on platform

  - name: stg_orders 
    description: Contains every unique order on platform 

  - name: stg_order_items
    description: Breakdown of order into items 

  - name: stg_events 
    description: Contains every unique event on platform      